keys:
  - &Main age1nahmfd6uh5f8ugmayz2q5vr7d2j2w8ev30cm2c6ug7lm3acx8u7q3z0q88
  - &Elisheva age1wllrsxvpmcsnkhk0n62cfm3763uv9kqpm34wzhx5h5n45dfq3geqgvcwjt
  - &Moontier age1nt2n6w93f2pykhg286np6m7v4vhdcxx0nr7ah72wwke6xt7u2uzsp3pc4g
  - &Centuria age1d2x47zljkkc02aez33ulqx7yrun9advqq3lefwwhzz0928zkff7qygz9eq
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - age:
      - *Main
      - *Elisheva
      - *Moontier
      - *Centuria
