keys:
  - &Elisheva age1nahmfd6uh5f8ugmayz2q5vr7d2j2w8ev30cm2c6ug7lm3acx8u7q3z0q88
  - &Moontier age1eq9rh8655chcn7j5837plpf2hux89qxxlt9mehdnfqdpak2arslsy3w7y3
creation_rules:
  - path_regex: Moontier/network/secrets.yaml$
    key_groups:
    - age:
      - *Elisheva
      - *Moontier
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *Elisheva
      - *Moontier
