keys:
  - &Elisheva age1evrxhkekty6ltj9a8rdeyjml2qeeynh40ghj3hywgnpdy2uq2u4q2a8uyn
  - &Moontier age1fhad5cu8sw0rcyejcq9gwgjp92dghe068yjn75euk3a26wwkug9q596f0h
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
    - age:
      - *Elisheva
      - *Moontier
