name = "MoontierSRV"
author = "rPlakama"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fb832357e86b44b449e3021f099a001fdbd63451bed9e0f2c5150c2b3a6e3a0"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
