name = "MoontierSRV"
author = "rPlakama"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a5ce574a34402d1c41884f7e6263e78819ec5affa1a00276fe5773196f92f94"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
