name = "MoontierSRV"
author = "rPlakama"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32aa8e924f9a4e7033af45baae10eb69ee3c3ee53800e42a141940edf9e4f208"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
