name = "additionals"
author = "rplk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef77f5791a53c6611faa1b5c218bcacc9cd45ee61d8f5abe054559430164e3f7"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
