name = "additionals"
author = "rplk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cae362231baa4a932cd326fe76b731d816e82313e84a07e7db4618ec03eaf95"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
