{
  config,
  lib,
  ...
}:
let
  cfg = config.optionals.features.nginx;
  currentIP = "192.168.1.106";
  domain = "moontier.online";
in
{
  options.optionals.features.nginx = {
    enable = lib.mkOption {
      type = lib.types.bool;
      description = "Nginx with Let's Encrypt via Hetzner DNS-01";
      default = false;
    };

    proxyServices = lib.mkOption {
      type = lib.types.attrsOf lib.types.port;
      default = { };
      description = "Autogenerated sufix *.moontier.online";
    };
  };

  config = lib.mkIf cfg.enable {
    sops.secrets."hetzner/api" = {
      owner = "acme";
      group = "acme";
      mode = "0400";
    };

    networking.firewall.allowedTCPPorts = [
      80
      443
    ];

    security.acme = {
      acceptTerms = true;
      defaults.email = "rPlakama@proton.me";
      certs."${domain}" = {
        domain = "${domain}";
        extraDomainNames = [ "*.${domain}" ];
        dnsProvider = "hetzner";
        environmentFile = config.sops.secrets."hetzner/api".path;
        dnsPropagationCheck = true;
        group = "nginx";
      };
    };

    services.nginx = {
      enable = true;
      recommendedGzipSettings = true;
      recommendedOptimisation = true;
      recommendedProxySettings = true;
      recommendedTlsSettings = true;

      virtualHosts = (
        lib.mapAttrs' (
          name: port:
          lib.nameValuePair "${name}.${domain}" {
            useACMEHost = "${domain}";
            forceSSL = true;
            extraConfig = ''
              allow 192.168.1.0/24;
              allow 100.64.0.0/10;
              allow 127.0.0.1;
              deny all;
            '';

            locations."/" = {
              proxyPass = "http://${currentIP}:${toString port}";
              proxyWebsockets = true;
            };
          }
        ) cfg.proxyServices
      );
    };
  };
}
