name = "MoontierSRV"
author = "rPlakama"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "615118740d2b0c7806edafe672e8c80fa3800eb9379b5d5c89f08c3e9469bd08"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
