name = "additionals"
author = "rplk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39f651b06dcb0a3960c38f905e7c61bc147bfce0af36211a84f443c49d5fdf6e"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
