name = "additionals"
author = "rplk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ae5c80bddfa89a2e76fcf85e7f9914e9d9d40da921b489c71404d116ea81a5b"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
