name = "additionals"
author = "rplk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f88b0725b2e239f04c9d129738ff6499436cf294a7c0498520ff870318e54205"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
