name = "additionals"
author = "rplk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c20355048f618541b13b3c83b561b407c8315f6997ffd204110fb0044b113ae"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
