name = "additionals"
author = "rplk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b53dc1954217899ee9382351b7a8e594eba863c0b058d6bbd84639d58952c89"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
