name = "additionals"
author = "rplk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "753dd4f58f8e21b26d0755e52a51aefa6ca39d3b9361588b8c7558734835670d"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
